ui:
  show_path: true
  show_lines: true
  show_hints: false
  submenu_symbol: ">"

binds:
  quit: "q"
  back: "h"

menu:
  - key: "u"
    desc: Utilities
    submenu:
      - key: "k"
        desc: Kitty
        cmd: kitty
      - key: "f"
        desc: Firefox
        cmd: firefox
      - key: "s"
        desc: Scripts
        submenu:
          - key: "w"
            desc: Wallpaper
            cmd: bash $HOME/.config/scripts/wallswitch
            # add more here later
      - key: "p"
        desc: toki pona
        submenu:
          - key: "n"
            desc: Number Converter
            cmd: kitty -e nanpa
          - key: "l"
            desc: Linku.la TUI
            cmd: kitty -e echo "fix later" # add this when script is done
      - key: "t"
        desc: Tools
        submenu:
          - key: "b"
            desc: Btop
            cmd: kitty -e btop
  - key: "s"
    desc: Social
    submenu:
      - key: "v"
        desc: Vesktop
        cmd: vesktop
      - key: "m"
        desc: Matrix (cinny)
        cmd: cinny
      - key: "i"
        desc: IRC
        submenu:
          - key: "l"
            desc: Liberachat
            cmd: kitty -e catgirl liberachat
          - key: "t"
            desc: Tildechat
            cmd: kitty -e catgirl tildechat
          - key: "u"
            desc: Undernet
            cmd: kitty -e catgirl undernet
  - key: "g"
    desc: Games
    submenu:
      - key: "s"
        desc: Steam
        cmd: steam
      - key: "g"
        desc: Genshin Impact
        cmd: an-anime-game-launcher
      - key: "c"
        desc: Celeste
        cmd: steam -applaunch 504230
      - key: "n"
        desc: Noita
        cmd: steam --applaunch 881100
      - key: "d"
        desc: Geometry Dash
        cmd: steam -applaunch 322170
  - key: "m"
    desc: Multimedia
    submenu:
      - key: "o"
        desc: OBS Studio
        cmd: flatpak run com.obsproject.Studio
      - key: "k"
        desc: Kdenlive
        cmd: kdenlive
      - key: "d"
        desc: Krita
        cmd: krita
      - key: "b"
        desc: Blender
        cmd: blender
      - key: "g"
        desc: GIMP
        cmd: gimp
  - key: "p"
    desc: Power
    submenu:
      - key: "l"
        desc: Lock
        cmd: hyprlock
      - key: "s"
        desc: Suspend
        cmd: systemctl suspend
      - key: "r"
        desc: Reboot
        cmd: systemctl reboot
      - key: "u"
        desc: Reboot to UEFI
        cmd: systemctl reboot --firmware-setup
      - key: "p"
        desc: Power Down
        cmd: systemctl poweroff
