[config]

[templates.niri]
input_path = '~/.config/matugen/templates/niri-colors.kdl'
output_path = '~/.config/niri/colors.kdl'
post_hook = 'niri msg action load-config-file'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.hyprland]
input_path = '~/.config/matugen/templates/hypr-colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel-colors.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.spotify]
input_path = '~/.config/matugen/templates/spicetify-colors.ini'
output_path = '~/.config/spicetify/Themes/Sleek/color.ini'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'

[templates.vesktop]
input_path = '~/.config/matugen/templates/vesktop.css'
output_path = '~/.config/vesktop/themes/midnight-discord.css'

[templates.web]
input_path = "~/.config/matugen/templates/web-colors.css"
output_path = "~/programs/web/lothlorien/colors.css"


[templates.obsidian]
input_path = '~/.config/matugen/templates/obsidian-colors.json'
output_path = '~/Documents/Vault/.obsidian/plugins/obsidian-style-settings/data.json'
post_hook = '''sed -E -i 's/("accentColor": ")[^"]*(")/\\1{{colors.surface.default.hex}}\\2/g' ~/Documents/Vault/.obsidian/appearance.json'''
